services:
  fp-svc:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        final-project: https://github.com/cpainter7362/playground.git
    container_name: fp-container
    ports:
      - "8081:7901"
    volumes:
      - type: bind
        source: ./volumes/final-project/config/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./volumes/final-project/config/conf.d
        target: /etc/nginx/conf.d

  hp-svc:
    image: nginx:latest
    container_name: hp-container
    volumes:
      - type: bind
        source: ./volumes/home-page/config/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./volumes/home-page/config/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./volumes/home-page/home/html
        target: /usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - php_svc

  php_svc:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php-container
    volumes:
      - ./volumes/home-page/home/html:/usr/share/nginx/html
    env_file:
      - ./volumes/php_mysql.env
    depends_on:
      - db_svc

  db_svc:
    image: mysql:8.0.41
    container_name: mysql-container
    env_file:
      - ./volumes/mysql/.env
      - ./volumes/php_mysql.env
    volumes:
      - ./volumes/mysql/db_contents:/var/lib/mysql
      - ./volumes/mysql/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "3311:3306"

  watchdog-svc:
    image: alpine:latest
    container_name: watchdog-container
    stdin_open: true
    tty: true
    restart: unless-stopped