services:
  http-svc:
    image: nginx:latest
    container_name: http-container
    ports:
      - "8089:80"
    volumes:
      - type: bind
        source: ./volumes/config/conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./volumes/html
        target: /usr/share/nginx/html

  php-svc:
    image: php:8.1-fpm-alpine
    container_name: php-container
    volumes:
      - type: bind
        source: ./volumes/html
        target: /usr/share/nginx/html